### ISSUE TITLE
unknown command `lmove`

### ISSUE THREAD

**Issue by jwoertink** [mosquito-cr/mosquito#132]
Just upgraded to the latest Mosquito and after deploying, my workers all break with this error

```
Unhandled exception in spawn: ERR unknown command `lmove`, with args beginning with: `mosquito:waiting:event_save_worker`, `mosquito:pending:event_save_worker`, `RIGHT`, `LEFT`,  (Redis::Error)
  from /home/runner/work/joysticktv/joysticktv/lib/redis/src/parser.cr:54:9 in 'read'
  from /home/runner/work/joysticktv/joysticktv/lib/redis/src/connection.cr:406:7 in 'run'
  from /home/runner/work/_temp/crystal-1.10.1-true-undefined/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```

Please include some details:

Crystal version: 1.10.1
Mosquito Shard version: 1.0.2
Redis: 0.7.1

**Comment by robacarp** [comment]
This is because of an out of date redis version. You should be able to update redis and resolve.

**Comment by jwoertink** [comment]
Doesn't Mosquito lock to 0.7.x though?

https://github.com/mosquito-cr/mosquito/blob/703a90a71d22c5e0495633e0af1c0b5bbd606c26/shard.yml#L21

Or would I just add an override?

**Comment by robacarp** [comment]
Hmm...Something's amiss. I'm running the same stack as you are, but I don't get the error. From my shard.lock:

```yml
  mosquito:
    git: https://github.com/mosquito-cr/mosquito.git
    version: 1.0.2+git.commit.703a90a71d22c5e0495633e0af1c0b5bbd606c26

  redis:
    git: https://github.com/jgaskins/redis.git
    version: 0.7.1
```

The LMOVE command [had an associated bug](https://github.com/jgaskins/redis/issues/37) in the redis adapter, and the commit mentioned 0adfc34e53f061545c570c9362a010b903ecf429 was present going back to 0.7.0.

Can you post your shard.lock lines for mosquito and redis?

**Comment by jwoertink** [comment]
```
  mosquito:
    git: https://github.com/mosquito-cr/mosquito.git
    version: 1.0.2

  redis:
    git: https://github.com/jgaskins/redis.git
    version: 0.7.1
```

This is what the shard.lock had.
